### ISSUE TITLE
Nie działa z BeautifulSoup 4.8

### ISSUE THREAD

**Issue by emkael** [emkael/pzbs-ranking#18]
```
Traceback (most recent call last):
  File "scripts/statics-compile.py", line 34, in <module>
    print template.prettify().encode('utf-8')
  File "/usr/local/lib/python2.7/dist-packages/bs4/element.py", line 1177, in prettify
    return self.decode(True, formatter=formatter)
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 588, in decode
    indent_level, eventual_encoding, formatter)
  File "/usr/local/lib/python2.7/dist-packages/bs4/element.py", line 1135, in decode
    indent_contents, eventual_encoding, formatter
  File "/usr/local/lib/python2.7/dist-packages/bs4/element.py", line 1212, in decode_contents
    formatter))
  File "/usr/local/lib/python2.7/dist-packages/bs4/element.py", line 1135, in decode
    indent_contents, eventual_encoding, formatter
  File "/usr/local/lib/python2.7/dist-packages/bs4/element.py", line 1212, in decode_contents
    formatter))
  File "/usr/local/lib/python2.7/dist-packages/bs4/element.py", line 1135, in decode
    indent_contents, eventual_encoding, formatter
  File "/usr/local/lib/python2.7/dist-packages/bs4/element.py", line 1212, in decode_contents
    formatter))
  File "/usr/local/lib/python2.7/dist-packages/bs4/element.py", line 1135, in decode
    indent_contents, eventual_encoding, formatter
  File "/usr/local/lib/python2.7/dist-packages/bs4/element.py", line 1212, in decode_contents
    formatter))
  File "/usr/local/lib/python2.7/dist-packages/bs4/element.py", line 1124, in decode
    pretty_print = self._should_pretty_print(indent_level)
  File "/usr/local/lib/python2.7/dist-packages/bs4/element.py", line 1172, in _should_pretty_print
    and self.name not in self.preserve_whitespace_tags
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by emkael** [comment]
Po pozbyciu się BS4 z repozytorium Debiana i instalacji przez `pip install -r requirements.txt --upgrade` - zaczęło działać.
